export {productRoutes} from './product.routes'
export {categoryRoutes} from './category.routes'
export {colorRoutes} from './color.routes'
export {sizeRoutes} from './size.routes'
export {productVariantRoutes} from './product-variant.routes'